export const LOAD_COMMENTS_BY_ID_REQUEST = "LOAD_COMMENTS_BY_ID_REQUEST" as const;
export const LOAD_COMMENTS_BY_ID_SUCCESS = "LOAD_COMMENTS_BY_ID_SUCCESS" as const;
export const LOAD_COMMENTS_BY_ID_FAILURE = "LOAD_COMMENTS_BY_ID_FAILURE" as const;

export const LOAD_COMMENTS_REQUEST = "LOAD_COMMENTS_REQUEST" as const;
export const LOAD_COMMENTS_SUCCESS = "LOAD_COMMENTS_SUCCESS" as const;
export const LOAD_COMMENTS_FAILURE = "LOAD_COMMENTS_FAILURE" as const;
